package types

// DO NOT EDIT. THIS FILE WAS AUTOMATICALLY GENERATED

// SoftLayer_Hardware_Component_Partition_Template - The
// SoftLayer_Hardware_Component_Partition_Template data type contains general information relating to a
// single SoftLayer partition template. Partition templates group 1 or more partition configurations
// that can be used to predefined how a hard drives partitions will be configured.
type SoftLayer_Hardware_Component_Partition_Template struct {

	// Account - A partition template's associated [[SoftLayer_Account|Account]].
	Account *SoftLayer_Account `json:"account"`

	// AccountId - A partition template's owner. The [[SoftLayer_Account|Account]] that a template was
	// created by.
	AccountId int `json:"accountId"`

	// Data - An individual partition for a partition template. This is identical to
	// 'partitionTemplatePartition' except this will sort unix partitions.
	Data []*SoftLayer_Hardware_Component_Partition_Template_Partition `json:"data"`

	// DataCount - A count of an individual partition for a partition template. This is identical to
	// 'partitionTemplatePartition' except this will sort unix partitions.
	DataCount uint64 `json:"dataCount"`

	// Description - no documentation
	Description string `json:"description"`

	// ExpireDate - <nil>
	ExpireDate string `json:"expireDate"`

	// Id - no documentation
	Id int `json:"id"`

	// PartitionOperatingSystem - A partition template's associated
	// [[SoftLayer_Hardware_Component_Partition_OperatingSystem|Operating System]].
	PartitionOperatingSystem *SoftLayer_Hardware_Component_Partition_OperatingSystem `json:"partitionOperatingSystem"`

	// PartitionOperatingSystemId - A partition template's associated
	// [[SoftLayer_Hardware_Component_Partition_OperatingSystem|Operating System]] Id.
	PartitionOperatingSystemId int `json:"partitionOperatingSystemId"`

	// PartitionTemplatePartition - no documentation
	PartitionTemplatePartition []*SoftLayer_Hardware_Component_Partition_Template_Partition `json:"partitionTemplatePartition"`

	// PartitionTemplatePartitionCount - A count of an individual partition for a partition template.
	PartitionTemplatePartitionCount uint64 `json:"partitionTemplatePartitionCount"`

	// StatusCode - no documentation
	StatusCode string `json:"statusCode"`

	// TemplateType - A partition template's Type. - template generated by softlayer. - templates generated
	// by SoftLayer customers.
	TemplateType string `json:"templateType"`
}

func (softlayer_hardware_component_partition_template *SoftLayer_Hardware_Component_Partition_Template) String() string {
	return "SoftLayer_Hardware_Component_Partition_Template"
}
