package types

// DO NOT EDIT. THIS FILE WAS AUTOMATICALLY GENERATED

// SoftLayer_Billing_Item_Software_Component_OperatingSystem_Addon_Citrix_Essentials - The
// SoftLayer_Billing_Item_Software_Component_OperatingSystem_Addon_Citrix_Essentials data type contains
// general information relating to a single SoftLayer billing item for Citrix Essentials software
// components.
type SoftLayer_Billing_Item_Software_Component_OperatingSystem_Addon_Citrix_Essentials struct {
}

func (softlayer_billing_item_software_component_operatingsystem_addon_citrix_essentials *SoftLayer_Billing_Item_Software_Component_OperatingSystem_Addon_Citrix_Essentials) String() string {
	return "SoftLayer_Billing_Item_Software_Component_OperatingSystem_Addon_Citrix_Essentials"
}

// SoftLayer_Billing_Item_Software_Component_OperatingSystem_Addon_Citrix_Essentials_Extended is SoftLayer_Billing_Item_Software_Component_OperatingSystem_Addon_Citrix_Essentials with all maskable types.
type SoftLayer_Billing_Item_Software_Component_OperatingSystem_Addon_Citrix_Essentials_Extended struct {
	SoftLayer_Billing_Item_Software_Component_OperatingSystem_Addon_Citrix_Essentials

	// Resource - The Citrix Essentials software component that a billing item is associated with.
	Resource *SoftLayer_Software_Component `json:"resource"`
}

func (softlayer_billing_item_software_component_operatingsystem_addon_citrix_essentials *SoftLayer_Billing_Item_Software_Component_OperatingSystem_Addon_Citrix_Essentials_Extended) String() string {
	return "SoftLayer_Billing_Item_Software_Component_OperatingSystem_Addon_Citrix_Essentials"
}
